name: Get FSU Instructors
on:
  workflow_dispatch:
jobs:
  run:
    name: Get & Commit
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          repository: DennisTsar/course-evals

      # Set up Java environment for the next steps
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      # Build & run application - update instructors file
      - name: Run
        run: ./gradlew fsu:run
        
      # Update repo with generated file
      - name: Add & Commit
        id: git
        run: |
          cd local
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git checkout master
          git add .
          git commit -m "Get FSU Data"
          git push
