name: "USF: Update Teaching Data"
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
jobs:
  triage:
    name: Get & Commit
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Java environment for the next steps
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      # Build & run application - get latest teaching data
      - name: Run
        run: ${{ inputs.command }} --args="-teaching"

      # Update repo with generated files
      - name: Add & Commit
        id: git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout master
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "USF: Updated teaching data"
            git push
          else
            echo "CHANGE=false" >> $GITHUB_OUTPUT
          fi